### ISSUE TITLE
Function of the type hierarchy

### ISSUE THREAD

**Issue by timur-han** [friemen/metam#1]
Hi,

A question regarding the type hierarchy of the defmetamodel macro. When a keyword is derived from anothor one. What does it imply about the metamodel? I thought it would enable us to inherit structural properties but I guess it does not work like. For instance we have the following set-up:

(derive ::a ::b)
{::b {::inherited [string?]}
::a {::c [string?]}

In this case we cannot use ::inherited in ::a although it's actually a parent property. Is this true or am I doing sth wrong?

**Comment by friemen** [comment]
In Version 1.0.7 the hierarchy is used solely for the defaults multimethod.
But your expectation for inheritance sounds like a reasonable feature.

I just implemented field inheritance and deployed a snapshot to Clojars (https://clojars.org/metam/core/versions/1.1.0-SNAPSHOT).
Please check if that fits your needs. If yes, I'd create a non-snapshot release.

**Comment by friemen** [comment]
Released 1.1.0 on Clojars.
